title: "Lanfeng Li"
name: "Lanfeng Li"
description: "Ph.D. Candidate in Economics, Georgetown University"

# IMPORTANT: project site settings
url: https://lanfengli1992.github.io
baseurl: "/personal-website"

# REMOVE this (it's wrong and causes your error):
# theme: academicpages

# Use the correct remote theme (what academicpages is built on)
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

collections:
  pages:
    output: true
    permalink: /:path/


markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

# Sidebar info (example)
author:
  name: "Lanfeng Li"
  avatar: "images/profile.jpg"
  bio: "Ph.D. Candidate in Economics, Georgetown University"
  location: "Arlington, VA"
  links:
    - label: "Email"
      url: "mailto:ll1077@georgetown.edu"
      icon: "fas fa-envelope"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/lanfeng-li-07704454/"
      icon: "fab fa-linkedin"

