locale: "en-US"
site_theme: "default" # Currently available options are "default", "air"
title: "Lanfeng Li"
name: "Lanfeng Li"
description: "Ph.D. Candidate in Economics, Georgetown University"

url: https://lanfengli1992.github.io
baseurl: "/personal-website"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap


# Sidebar info (example)
author:
  name: "Lanfeng Li"
  avatar: "images/profile.jpg"
  bio: "Ph.D. Candidate in Economics, Georgetown University"
  location: "Arlington, VA"
  links:
    - label: "Email"
      url: "mailto:ll1077@georgetown.edu"
      icon: "fas fa-envelope"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/lanfeng-li-07704454/"
      icon: "fab fa-linkedin"

