locale: "en-US"
site_theme: "default" # Currently available options are "default", "air"
title: "Lanfeng Li"
name: "Lanfeng Li"
description: "Ph.D. Candidate in Economics, Georgetown University"

url: https://lanfengli1992.github.io
baseurl: "/personal-website"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap


@import "minimal-mistakes/skins/{{ site.minimal_mistakes_skin | default: 'default' }}"; // keep your skin
@import "minimal-mistakes";

// Make the avatar square and nicely cropped
.page__sidebar .author__avatar img {
  width: 180px;   // adjust to taste
  height: 180px;  // keep equal to width for a square frame
  object-fit: cover;
  border-radius: 6px; // change to 0 for perfectly square; increase for more rounded
}


# Sidebar info (example)
author:
  name: "Lanfeng Li"
  avatar: "images/profile.jpg"
  bio: "Ph.D. Candidate in Economics, Georgetown University"
  location: "Arlington, VA"
  links:
    - label: "Email"
      url: "mailto:ll1077@georgetown.edu"
      icon: "fas fa-envelope"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/lanfeng-li-07704454/"
      icon: "fab fa-linkedin"

